id: csswarrior_feed_padding
learningObjectives:
  - Add padding to the feed toggle component
hints:
  - Use the 'px' bootstrap class to add padding to the feed toggle component
  - Change the padding of the feed toggle component to "px-4" in the homepage
startFlow:
  do:
    - actionId: bot_message
      params:
        person: keen
        messages:
          - text: "Good work! Now, let's move on to the next step."
            delay: 700
          - text: "As you can see, the feed toggle component is not properly aligned with the list of cards."
            delay: 800
          - text: "You can use a bootstrap class to add a horizontal padding to the feed toggle component. Add padding of 1.5rem to the feed toggle component."
            delay: 1000
          - text: "Create a PR when you're done and I'll review it."
            delay: 1300

githubActions:
  backend:
    capabilities:
      - axios
      - dotenv
    testFile: "test.js"
  frontend:
    capabilities:
      - jest-puppeteer
      - puppeteer@18.1.0
    testFile: "test2.test.js"

trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: "${eventType}"
      cases:
        github_pr_opened:
          do:
            - actionId: github_pr_comment
              params:
                person: keen
                message: "On it! I'll review the changes as soon as possible!"
            - actionId: bot_message
              params:
                person: keen
                messages:
                  - text: "On it! I'll review the changes as soon as possible!"
                    delay: 1500
        github_pr_workflow_complete_success:
          do:
            - actionId: bot_message
              params:
                person: keen
                messages:
                  - text: Looking good! You can merge the PR now.
                    delay: 1500
            - actionId: github_pr_approve
              params:
                person: keen
                message: Looking good! You can merge the PR now.
        github_pr_workflow_complete_failure:
          do:
            - actionId: github_pr_reject
              params:
                person: keen
                message: Some PR checks are failing. Please look into it and create a new PR.

            - actionId: bot_message
              params:
                person: keen
                messages:
                  - text: Some PR checks are failing. Please look into it and create a new PR.
                    delay: 2500
        github_pr_merged:
          do:
            - actionId: finish_step
